#!/bin/sh
# Removes the rhispertoold symlink created by postinst - dpkg only tracks
# files it installed directly, not this manually-created symlink.
set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    rm -f /usr/bin/rhispertoold
fi

exit 0
